apiVersion: apps/v1
kind: Deployment
metadata:
  name: takehome-service
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: takehome-service
  template:
    metadata:
      labels:
        app: takehome-service
    spec:
      containers:
      - name: takehome-service
        image: #{IMAGE}
        env:
        - name: POSTGRES_DSN
          value: "#{POSTGRES_DSN}"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: takehome-service
spec:
  selector:
    app: takehome-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: grpc
      port: 9008
      targetPort: 9008
    - name: metrics
      port: 8081
      targetPort: 8081
  type: LoadBalancer